#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --user "$POSTGRES_ROOT_USER" --dbname "$POSTGRES_DEFAULT_DB" <<-EOSQL
	CREATE USER "$PG_APP_USER" WITH PASSWORD '$PG_APP_PASSWORD';
	CREATE DATABASE "$PG_APP_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$PG_APP_DB" TO "$PG_APP_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --user "$POSTGRES_ROOT_USER" --dbname "$PG_APP_DB" <<-EOSQL
	GRANT ALL ON SCHEMA "$PG_APP_SCHEMA" TO "$PG_APP_USER";
EOSQL
